## By Permno

O objetivo desse notebook é criar um conjunto de tabelas na extensão .csv onde cada tabela representa uma série diária de uma ação a partir de dois dataframes, um contendo dados diários de firmas e suas caracaterísticas e outro contendo dados de localização em percentis de fatores financeiros.

E.g. '10001.csv' será uma planilha (tabela) contendo a série temporal da ação cujo permno é o 10001.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# oculta mensagens de avisos
import warnings
warnings.filterwarnings("ignore")

In [3]:
# pd.set_option('display.max_columns', None)

In [4]:
# pd.set_option('display.max_rows', 10)

In [5]:
crsp = pd.read_csv('../input/table.csv')

In [6]:
crsp

,PERMNO,date,NAMEENDT,SHRCD,EXCHCD,SICCD,NCUSIP,TICKER,COMNAM,TSYMBOL,...,ACPERM,NWPERM,DLPRC,PRC,RET,SHROUT,CFACPR,OPENPRC,MARKETCAP,TAQ_TICKER
0,10001,20050103,NaN,11,3,4920.0,29274A10,EWST,ENERGY WEST INC,EWST,...,NaN,NaN,NaN,6.67000,-0.033333,2599.0,1.5,6.99000,1.733533e+04,EWST
1,10001,20050104,NaN,11,3,4920.0,29274A10,EWST,ENERGY WEST INC,EWST,...,NaN,NaN,NaN,6.51000,-0.023988,2599.0,1.5,6.51000,1.691949e+04,EWST
2,10001,20050105,NaN,11,3,4920.0,29274A10,EWST,ENERGY WEST INC,EWST,...,NaN,NaN,NaN,6.70000,0.029186,2599.0,1.5,6.52000,1.741330e+04,EWST
3,10001,20050106,NaN,11,3,4920.0,29274A10,EWST,ENERGY WEST INC,EWST,...,NaN,NaN,NaN,6.51000,-0.028358,2599.0,1.5,6.72000,1.691949e+04,EWST
4,10001,20050107,NaN,11,3,4920.0,29274A10,EWST,ENERGY WEST INC,EWST,...,NaN,NaN,NaN,6.54600,0.005530,2599.0,1.5,6.96000,1.701305e+04,EWST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16305334,93436,20201224,NaN,11,3,9999.0,88160R10,TSLA,TESLA INC,TSLA,...,NaN,NaN,NaN,661.77002,0.024444,947901.0,1.0,642.98999,6.272925e+08,TSLA
16305335,93436,20201228,NaN,11,3,9999.0,88160R10,TSLA,TESLA INC,TSLA,...,NaN,NaN,NaN,663.69000,0.002901,947901.0,1.0,674.51001,6.291124e+08,TSLA
16305336,93436,20201229,NaN,11,3,9999.0,88160R10,TSLA,TESLA INC,TSLA,...,NaN,NaN,NaN,665.98999,0.003465,947901.0,1.0,661.00000,6.312926e+08,TSLA
16305337,93436,20201230,NaN,11,3,9999.0,88160R10,TSLA,TESLA INC,TSLA,...,NaN,NaN,NaN,694.78003,0.043229,947901.0,1.0,672.00000,6.585827e+08,TSLA
16305338,93436,20201231,NaN,11,3,9999.0,88160R10,TSLA,TESLA INC,TSLA,...,NaN,0.0,0.0,705.66998,0.015674,947901.0,1.0,699.98999,6.689053e+08,TSLA

In [7]:
factors = pd.read_csv('../input/table2.csv')

In [8]:
factors

,permno,date,pNYSE_size,pNYSE_value,pNYSE_prof,pNYSE_dur,pNYSE_valprof,pNYSE_fscore,pNYSE_debtiss,pNYSE_repurch,...,pNYSE_season,pNYSE_indrrev,pNYSE_indrrevlv,pNYSE_indmomrev,pNYSE_ciss,pNYSE_price,pNYSE_age,pNYSE_shvol,pNYSE_exchsw,pNYSE_ipo
0,10001,01/2005,10.0,10.0,1.0,NaN,6.0,1,10.0,1.0,...,7.0,1.0,NaN,NaN,8.0,1.0,5,10.0,10,1
1,10002,01/2005,10.0,NaN,NaN,NaN,NaN,1,10.0,1.0,...,8.0,1.0,NaN,NaN,7.0,4.0,5,10.0,10,1
2,10012,01/2005,10.0,7.0,8.0,7.0,9.0,10,10.0,10.0,...,10.0,1.0,NaN,NaN,3.0,1.0,5,1.0,10,1
3,10025,01/2005,10.0,7.0,7.0,8.0,9.0,1,10.0,1.0,...,3.0,1.0,NaN,NaN,9.0,2.0,5,10.0,10,1
4,10026,01/2005,9.0,6.0,9.0,7.0,10.0,10,10.0,10.0,...,5.0,6.0,6.0,5.0,6.0,8.0,5,9.0,10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729025,93422,12/2019,7.0,10.0,NaN,10.0,NaN,1,1.0,10.0,...,1.0,7.0,NaN,NaN,1.0,1.0,7,1.0,10,1
729026,93423,12/2019,5.0,1.0,7.0,1.0,1.0,10,1.0,10.0,...,10.0,6.0,NaN,NaN,10.0,6.0,7,2.0,10,1
729027,93426,12/2019,9.0,6.0,8.0,6.0,9.0,10,1.0,10.0,...,3.0,8.0,9.0,10.0,4.0,5.0,7,8.0,10,1
729028,93434,12/2019,10.0,9.0,2.0,9.0,6.0,1,1.0,10.0,...,3.0,5.0,NaN,NaN,1.0,1.0,7,10.0,10,1
729029,93436,12/2019,1.0,1.0,4.0,1.0,1.0,10,1.0,1.0,...,9.0,4.0,NaN,NaN,1.0,10.0,7,1.0,10,1

In [9]:
# todos permnos no dataframe factors
factors_permno = factors['permno'].unique()

In [10]:
# todos permnos no dataframe crsp
crsp_permno = crsp['PERMNO'].unique()

In [11]:
# somente os permnos que estão em ambos os dataframes
permnos = np.intersect1d(factors_permno, crsp_permno)

In [12]:
permnos

array([10001, 10002, 10012, ..., 93434, 93435, 93436], dtype=int64)

In [13]:
for i in permnos:
    """
    Primeiro, criaremos um dataframe com os dados CRSP para cada PERMNO
    Neste dataframe, indexaremos o DIA (nessa base os dados já se encontram na frequência diária)
    """
    df = crsp[crsp['PERMNO'] == i]
    df['date'] = df['date'].apply(lambda x: pd.to_datetime(str(x), format='%Y%m%d'))
    df.set_index('date', inplace=True)

    """
    Segundo, criaremos um dataframe com os dados dos FACTORS para cada PERMNO
    Neste dataframe, indexaremos o DIA (nessa base os dados se encontram na frequência mensal)
    """
    df_ = factors[factors['permno'] == i]
    df_['date'] = pd.to_datetime(df_['date'])
    df_.set_index('date', inplace=True)

    start = min(df_.index[0], df.index[0]) # pegando a primeira data entre as primeiras datas dos dois dataframes
    end = max(df_.index[len(df_) - 1], df.index[len(df) - 1]) # pegando a última data entre as últimas datas dos dois dataframes
    days = pd.date_range(start = start, end = end, freq='D')
    
    df_ = df_.reindex(days, method='ffill') # função que reindexa o dataframe para frequência diária utilizando o método de preenchimento para as novas linhas

    """
    Por fim, agora temos dois dataframes na mesma frequência.
    Um com dados CRSP e outro com dados dos FACTORS
    Basta dar um merge entre os dois e finalizamos a iteração fazendo o download em csv do dataframe
    """
    df_final = pd.merge(df, df_, left_index = True, right_index = True)
    df_final = df_final.drop('permno', axis=1)
    output_path = "..\\output\\by_permno\\{}.csv".format(i)
    df_final.to_csv(output_path, sep=',', encoding='utf-8')